# pytorch

### 基础数据类型

In [5]:
import torch

a = torch.Tensor(2,2)

b = torch.DoubleTensor(2,2)

c = torch.FloatTensor(2,2)

d = torch.Tensor([[1, 2], [3, 4]])

e = torch.zeros(2, 2)

f = torch.ones(2, 2)

g = torch.eye(2, 2)

h = torch.randn(2, 2)

i = torch.randperm(4)

j = torch.arange(1, 20, 2)

a, b, c, d, e, f, g, h, i, j

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]], dtype=torch.float64),
 tensor([[9.7347e-39, 9.0919e-39],
         [1.0102e-38, 4.5919e-39]]),
 tensor([[1., 2.],
         [3., 4.]]),
 tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 0.],
         [0., 1.]]),
 tensor([[-2.0615,  0.9363],
         [ 2.7582,  0.9815]]),
 tensor([3, 1, 2, 0]),
 tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]))

### 运算

In [14]:
import torch

a = torch.randn(2, 3)

print(a)

b = torch.abs(a)

print("abs  a:", b)

c = torch.add(a, b)

print("add a+b to c:", c)

d = torch.clamp(c, 0.5, 1)

print("clamp c to d: ", d)

e = torch.div(c, d)

print("c div d to e:", e)

f = torch.pow(a, 2)

print("a pow 2 to f :", f)

##矩阵乘
g = torch.mm(a, b.T)

print("a * b to g:", g)

##矩阵向量乘
h = torch.mv(torch.randn(2, 3), torch.randn(3))

print("(2, 3) * (3):", h)

tensor([[ 0.8862, -0.1900, -0.1777],
        [ 0.5224, -0.6162,  0.0290]])
abs  a: tensor([[0.8862, 0.1900, 0.1777],
        [0.5224, 0.6162, 0.0290]])
add a+b to c: tensor([[1.7724, 0.0000, 0.0000],
        [1.0447, 0.0000, 0.0579]])
clamp c to d:  tensor([[1.0000, 0.5000, 0.5000],
        [1.0000, 0.5000, 0.5000]])
c div d to e: tensor([[1.7724, 0.0000, 0.0000],
        [1.0447, 0.0000, 0.1158]])
a pow 2 to f : tensor([[0.7853, 0.0361, 0.0316],
        [0.2729, 0.3797, 0.0008]])
a * b to g: tensor([[ 0.7176,  0.3406],
        [ 0.3509, -0.1060]])
(2, 3) * (3): tensor([ 1.3230, -0.0935])
